default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: WARNING
  username: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: movie_booking_system
  username: postgres
  password: postgres

test:
  <<: *default
  database: movie_booking_test
  username: postgres
  password: postgres
